### PR TITLE
Add max connection to variable

### PR DESCRIPTION
**Pull request by shibaPuppy**
should be able to change the max connection

### CODE REVIEW

**Comment by shibaPuppy** [comment]
@dtantsur 
it uses about 1000EA bare metal nodes.
so it would be nice to have a max connection option variable.

**Comment by dtantsur** [comment]
You're also changing the default, is it intended? I assume it's going to increase the RAM usage.

**Comment by shibaPuppy** [comment]
@dtantsur 
it's no significant increase in memory usage in the dev environment.

before
```
kubectl top -n test po metal3-ironic-6fddcb67ff-d8466
NAME                             CPU(cores)   MEMORY(bytes)
metal3-ironic-6fddcb67ff-d8466   17m          352Mi
```

after
```
kubectl top -n test po metal3-ironic-645cf85dcc-khkn7
NAME                             CPU(cores)   MEMORY(bytes)
metal3-ironic-645cf85dcc-khkn7   83m          355Mi
```

**Comment by dtantsur** [comment]
I'm not a huge mysql specialist, but putting 1024 in http://www.mysqlcalculator.com/ gives me a huge increase. I'm okay with returning to the mysql default of 150 (which already adds 200M of RAM according to the calculator), but not to such a huge value.

**Pull request closed without merging**
