### PR TITLE
Add max connection to variable

### PR DESCRIPTION
**Pull request by shibaPuppy**
same content as the previous PR.
https://github.com/metal3-io/mariadb-image/pull/10

### CODE REVIEW

**Comment by tuminoid** [comment]
Mariadb image SHA has been deleted from quay.io, causing this test failure.

I'm reverting the pinning in https://github.com/metal3-io/mariadb-image/pull/13 and after that this should be rebased and it'll pass.

**Comment by tuminoid** [comment]
#13 has merged, please rebase.

**Comment by shibaPuppy** [comment]
> #13 has merged, please rebase.

@tuminoid 
rebase completed.

**Review by tuminoid — APPROVED** [review]

**Pull request merged**
