### PR TITLE
Do not purge the users table, it removes system users

### PR DESCRIPTION
**Pull request by dtantsur**

### CODE REVIEW

**Comment by tuminoid** [comment]
/hold 
Probably good to go, but I want to verify manually. I'll remove hold later today.

**Comment by tuminoid** [comment]
/unhold

It works nicely, two users are left `ironic` and 'mariadb.sys`.

**Review by tuminoid — APPROVED** [review]
/lgtm

**Comment by tuminoid** [comment]
/cc @lentzi90 
LGTM this please.

**Review by lentzi90 — COMMENTED** [review]
/lgtm

**Pull request merged**
